services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prex_challenge_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html:delegated
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - prex-net

  db:
    image: mariadb:10.6
    container_name: prex_challenge_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"
    networks:
      - prex-net

  nginx:
    image: nginx:1.23-alpine
    container_name: prex_challenge_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - prex-net

volumes:
  db_data:

networks:
  prex-net:
    driver: bridge